# Generated by Django 6.0 for Course des Starters.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game", "0017_card_prints_and_rarities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=16,
                    ),
                ),
                ("pending_roll", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("turn_revision", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starterrace_created_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("turn_order", models.PositiveSmallIntegerField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="starterrace.game",
                    ),
                ),
                (
                    "starter_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="starterrace_players",
                        to="game.pokemoncard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starterrace_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["turn_order"]},
        ),
        migrations.AddField(
            model_name="game",
            name="current_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_turn_games",
                to="starterrace.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_starterrace_games",
                to="starterrace.player",
            ),
        ),
        migrations.CreateModel(
            name="Pawn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField()),
                ("position", models.SmallIntegerField(default=-1)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pawns",
                        to="starterrace.player",
                    ),
                ),
            ],
            options={"ordering": ["number"]},
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("roll", models.PositiveSmallIntegerField()),
                ("from_position", models.SmallIntegerField(blank=True, null=True)),
                ("to_position", models.SmallIntegerField(blank=True, null=True)),
                ("shortcut_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("shortcut_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("captured_pawns", models.JSONField(blank=True, default=list)),
                ("was_pass", models.BooleanField(default=False)),
                ("grants_extra_turn", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="starterrace.game",
                    ),
                ),
                (
                    "pawn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="starterrace.pawn",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="starterrace.player",
                    ),
                ),
            ],
            options={"ordering": ["sequence"]},
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_roll__isnull", True))
                | models.Q(("pending_roll__gte", 1), ("pending_roll__lte", 6)),
                name="starterrace_pending_roll_one_to_six",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("game", "user"),
                name="unique_starterrace_user_per_game",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("game", "turn_order"),
                name="unique_starterrace_turn_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                condition=models.Q(("turn_order__gte", 0), ("turn_order__lte", 3)),
                name="starterrace_turn_order_zero_to_three",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawn",
            constraint=models.UniqueConstraint(
                fields=("player", "number"),
                name="unique_starterrace_pawn_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawn",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 0), ("number__lte", 3)),
                name="starterrace_pawn_number_zero_to_three",
            ),
        ),
        migrations.AddConstraint(
            model_name="pawn",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", -1), ("position__lte", 43)),
                name="starterrace_pawn_position_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("game", "sequence"),
                name="unique_starterrace_move_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.CheckConstraint(
                condition=models.Q(("roll__gte", 1), ("roll__lte", 6)),
                name="starterrace_move_roll_one_to_six",
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_position__isnull", True),
                    ("pawn__isnull", True),
                    ("to_position__isnull", True),
                    ("was_pass", True),
                )
                | models.Q(
                    ("from_position__isnull", False),
                    ("pawn__isnull", False),
                    ("to_position__isnull", False),
                    ("was_pass", False),
                ),
                name="starterrace_move_payload_matches_pass",
            ),
        ),
    ]

