# Generated by Django 6.0.7 on 2026-08-04 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0010_types_reels_par_partie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PictionaryGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=16)),
                ('round_count', models.PositiveSmallIntegerField(choices=[(3, '3 manches'), (6, '6 manches'), (9, '9 manches')], default=6, help_text='Nombre de manches, donc de dessinateurs successifs.')),
                ('turn_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictionary_created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PictionaryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_order', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pictionary.pictionarygame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictionary_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['turn_order'],
            },
        ),
        migrations.CreateModel(
            name='PictionaryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawn_rounds', to='pictionary.pictionaryplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='pictionary.pictionarygame')),
                ('pokemon_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictionary_rounds', to='game.pokemoncard')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PictionaryGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('is_correct', models.BooleanField(default=False)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='pictionary.pictionaryplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='pictionary.pictionaryround')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PictionaryStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('points', models.JSONField(default=list)),
                ('color', models.CharField(default='#f6f9ff', max_length=7)),
                ('width', models.PositiveSmallIntegerField(default=4)),
                ('is_clear', models.BooleanField(default=False, help_text='Efface tout ce qui précède.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='pictionary.pictionaryround')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='pictionaryplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_pictionary_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='pictionaryplayer',
            constraint=models.UniqueConstraint(fields=('game', 'turn_order'), name='unique_pictionary_turn_order'),
        ),
        migrations.AddConstraint(
            model_name='pictionaryround',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='unique_pictionary_round_number'),
        ),
        migrations.AddConstraint(
            model_name='pictionaryguess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('round', 'player'), name='unique_correct_pictionary_guess'),
        ),
        migrations.AddIndex(
            model_name='pictionarystroke',
            index=models.Index(fields=['round', 'sequence'], name='pictionary__round_i_ef41fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pictionarystroke',
            constraint=models.UniqueConstraint(fields=('round', 'sequence'), name='unique_stroke_sequence_per_round'),
        ),
    ]
