# Generated by Django 6.0.8 on 2026-08-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metamorph', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metamorphplayer',
            name='unique_metamorph_user_per_game',
        ),
        migrations.AddField(
            model_name='metamorphplayer',
            name='bot_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='metamorphplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metamorph_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='metamorphplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('game', 'user'), name='unique_metamorph_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='metamorphplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('bot_name', ''), _negated=True), fields=('game', 'bot_name'), name='unique_metamorph_bot_name_per_game'),
        ),
        migrations.AddConstraint(
            model_name='metamorphplayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', True), models.Q(('bot_name', ''), _negated=True)), models.Q(('user__isnull', False), ('bot_name', '')), _connector='OR'), name='metamorph_valid_player_controller'),
        ),
    ]
