# Generated by Django 6.0.7 on 2026-08-03 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('sprite_url', models.URLField()),
                ('is_legendary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pokedex_id'],
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_fr', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=6)),
                ('direction', models.SmallIntegerField(default=1)),
                ('current_turn_number', models.PositiveSmallIntegerField(default=0)),
                ('card_sequence_counter', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('active_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.pokemontype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_order', models.PositiveSmallIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('has_called_uno', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['turn_order'],
            },
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('PIOCHE', 'Pioche'), ('MAIN', 'Main'), ('DEFAUSSE', 'Défausse')], default='PIOCHE', max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.game')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_cards', to='game.gameplayer')),
                ('pokemon_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='game.pokemoncard')),
            ],
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='primary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_cards', to='game.pokemontype'),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='secondary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_cards', to='game.pokemontype'),
        ),
        migrations.CreateModel(
            name='MoveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('DEBUT_PARTIE', 'Début de partie'), ('DISTRIBUTION', 'Distribution'), ('JOUER_CARTE', 'Carte jouée'), ('PIOCHER', 'Pioche'), ('MELANGE_DEFAUSSE', 'Mélange de la défausse'), ('FIN_PARTIE', 'Fin de partie')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_logs', to='game.game')),
                ('game_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamecard')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='game.gameplayer')),
                ('declared_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.pokemontype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games_played', models.PositiveIntegerField(default=0)),
                ('total_games_won', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_player_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('game', 'turn_order'), name='unique_turn_order_per_game'),
        ),
        migrations.AddIndex(
            model_name='gamecard',
            index=models.Index(fields=['game', 'location', 'order_index'], name='game_gameca_game_id_521d2e_idx'),
        ),
    ]
