# Generated by Django 6.0.7 on 2026-08-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_remove_legacy_type_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="active_tcg_type",
            field=models.CharField(
                blank=True,
                choices=[("grass", "Plante"), ("fire", "Feu"), ("water", "Eau"), ("lightning", "Électrique")],
                default="",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="movelog",
            name="declared_tcg_type",
            field=models.CharField(
                blank=True,
                choices=[("grass", "Plante"), ("fire", "Feu"), ("water", "Eau"), ("lightning", "Électrique")],
                default="",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="movelog",
            name="move_type",
            field=models.CharField(
                choices=[
                    ("DEBUT_PARTIE", "Début de partie"),
                    ("DISTRIBUTION", "Distribution"),
                    ("JOUER_CARTE", "Carte jouée"),
                    ("PIOCHER", "Pioche"),
                    ("MELANGE_DEFAUSSE", "Mélange de la défausse"),
                    ("FIN_PARTIE", "Fin de partie"),
                    ("ABANDON", "Partie fermée pour inactivité"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pokemoncard",
            name="tcg_type",
            field=models.CharField(
                choices=[("grass", "Plante"), ("fire", "Feu"), ("water", "Eau"), ("lightning", "Électrique")],
                default="grass",
                max_length=12,
            ),
        ),
    ]
