# Generated by Django 6.0.7 on 2026-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_active_tcg_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='active_tcg_type',
        ),
        migrations.RemoveField(
            model_name='movelog',
            name='declared_tcg_type',
        ),
        migrations.RemoveField(
            model_name='pokemoncard',
            name='action',
        ),
        migrations.RemoveField(
            model_name='pokemoncard',
            name='tcg_type',
        ),
        migrations.AddField(
            model_name='game',
            name='active_type',
            field=models.ForeignKey(blank=True, help_text='Type déclaré par le dernier joker joué.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_games', to='game.pokemontype'),
        ),
        migrations.AddField(
            model_name='game',
            name='selected_types',
            field=models.ManyToManyField(blank=True, help_text="Les types tirés au sort au démarrage : la pioche n'en contient pas d'autres.", related_name='games', to='game.pokemontype'),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='action',
            field=models.CharField(choices=[('NORMAL', 'Aucun effet'), ('DRAW_TWO', '+2'), ('DRAW_FOUR', '+4'), ('REVERSE', 'Inversion'), ('SHIELD', 'Protection')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='movelog',
            name='declared_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations', to='game.pokemontype'),
        ),
    ]
