# Generated by Django 6.0.7 on 2026-08-04 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_types_reels_par_partie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="profiles/avatars/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Refusée"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("pair_key", models.CharField(editable=False, max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "addressee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["requester", "status"], name="game_friend_request_89a319_idx"),
                    models.Index(fields=["addressee", "status"], name="game_friend_address_df8d63_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("requester", models.F("addressee")), _negated=True),
                        name="friendship_users_must_be_different",
                    )
                ],
            },
        ),
    ]
