# Generated by Django 6.0.7 on 2026-08-04 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_profile_avatar_profile_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACCEPTED", "Acceptée"),
                            ("DECLINED", "Refusée"),
                            ("CANCELLED", "Annulée"),
                            ("EXPIRED", "Expirée"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="game.game",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient", "status"], name="game_gamein_recipie_553461_idx"),
                    models.Index(fields=["sender", "status"], name="game_gamein_sender__7eae29_idx"),
                    models.Index(fields=["game", "status"], name="game_gamein_game_id_f42bdd_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sender", models.F("recipient")), _negated=True),
                        name="game_invitation_users_must_be_different",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("game", "recipient"),
                        name="unique_pending_game_invitation",
                    ),
                ],
            },
        ),
    ]
