# Generated by Django 6.0.7 on 2026-08-04 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_gameinvitation"),
        ("guesswho", "0001_initial"),
        ("pictionary", "0001_initial"),
        ("silhouette", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gameinvitation",
            name="unique_pending_game_invitation",
        ),
        migrations.RemoveIndex(
            model_name="gameinvitation",
            name="game_gamein_game_id_f42bdd_idx",
        ),
        migrations.AddField(
            model_name="gameinvitation",
            name="guesswho_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="guesswho.guesswhogame",
            ),
        ),
        migrations.AddField(
            model_name="gameinvitation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("POKE_UNO", "Poké-Uno"),
                    ("GUESSWHO", "Qui est-ce ?"),
                    ("SILHOUETTE", "Silhouette"),
                    ("PICTIONARY", "Pictionary"),
                ],
                default="POKE_UNO",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="gameinvitation",
            name="pictionary_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="pictionary.pictionarygame",
            ),
        ),
        migrations.AddField(
            model_name="gameinvitation",
            name="silhouette_game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="silhouette.silhouettegame",
            ),
        ),
        migrations.AlterField(
            model_name="gameinvitation",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="game.game",
            ),
        ),
        migrations.AddIndex(
            model_name="gameinvitation",
            index=models.Index(fields=["mode", "status"], name="game_gamein_mode_63089a_idx"),
        ),
        migrations.AddConstraint(
            model_name="gameinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("game__isnull", False),
                        ("guesswho_game__isnull", True),
                        ("mode", "POKE_UNO"),
                        ("pictionary_game__isnull", True),
                        ("silhouette_game__isnull", True),
                    ),
                    models.Q(
                        ("game__isnull", True),
                        ("guesswho_game__isnull", False),
                        ("mode", "GUESSWHO"),
                        ("pictionary_game__isnull", True),
                        ("silhouette_game__isnull", True),
                    ),
                    models.Q(
                        ("game__isnull", True),
                        ("guesswho_game__isnull", True),
                        ("mode", "SILHOUETTE"),
                        ("pictionary_game__isnull", True),
                        ("silhouette_game__isnull", False),
                    ),
                    models.Q(
                        ("game__isnull", True),
                        ("guesswho_game__isnull", True),
                        ("mode", "PICTIONARY"),
                        ("pictionary_game__isnull", False),
                        ("silhouette_game__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="game_invitation_has_one_valid_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("game__isnull", False), ("status", "PENDING")),
                fields=("game", "recipient"),
                name="unique_pending_game_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guesswho_game__isnull", False), ("status", "PENDING")),
                fields=("guesswho_game", "recipient"),
                name="unique_pending_guesswho_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("silhouette_game__isnull", False), ("status", "PENDING")),
                fields=("silhouette_game", "recipient"),
                name="unique_pending_silhouette_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pictionary_game__isnull", False), ("status", "PENDING")),
                fields=("pictionary_game", "recipient"),
                name="unique_pending_pictionary_invitation",
            ),
        ),
    ]
