# Generated by Django 6.0.7 on 2026-08-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_gameinvitation_unique_pending_game_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Compte temporaire créé pour jouer sans inscription.'),
        ),
    ]
