# Generated by Django 6.0.7 on 2026-08-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_profile_is_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points gagnés en accomplissant des quêtes, dépensés en boosters.'),
        ),
        migrations.CreateModel(
            name='BoosterOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_key', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(related_name='booster_openings', to='game.pokemoncard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='game.pokemoncard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pokemon_card__pokedex_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pokemon_card'), name='unique_collection_card_per_user')],
            },
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_key', models.CharField(max_length=40)),
                ('period_key', models.CharField(help_text='Jour (AAAA-MM-JJ) ou semaine ISO (AAAA-Wnn) concernée.', max_length=12)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quest_key'],
                'indexes': [models.Index(fields=['user', 'period_key'], name='game_questp_user_id_4a1fdb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'quest_key', 'period_key'), name='unique_quest_progress_per_period')],
            },
        ),
    ]
