# Generated by Django 6.0.7 on 2026-08-05 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_quests_collection_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_key', models.CharField(max_length=30)),
                ('source', models.CharField(blank=True, help_text="Clé de la quête qui l'a offert.", max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='collectioncard',
            options={'ordering': ['season', 'pokemon_card__pokedex_id']},
        ),
        migrations.RemoveConstraint(
            model_name='collectioncard',
            name='unique_collection_card_per_user',
        ),
        migrations.AddField(
            model_name='boosteropening',
            name='season',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='season',
            field=models.PositiveSmallIntegerField(default=1, help_text='Édition dont vient cette carte : 1 pour le Set de Base, 2 pour la série 151.'),
        ),
        migrations.AlterField(
            model_name='boosteropening',
            name='price',
            field=models.PositiveIntegerField(help_text='Points débités. Zéro pour un booster offert par une quête.'),
        ),
        migrations.AddConstraint(
            model_name='collectioncard',
            constraint=models.UniqueConstraint(fields=('user', 'pokemon_card', 'season'), name='unique_collection_card_per_user_and_season'),
        ),
        migrations.AddField(
            model_name='boosterticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='boosterticket',
            index=models.Index(fields=['user', 'opened_at'], name='game_booste_user_id_490a1d_idx'),
        ),
    ]
