# Generated by Django 6.0.7 on 2026-08-05 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_seasons_and_quest_boosters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectioncard',
            options={'ordering': ['season', 'pokemon_card__pokedex_id', 'variant']},
        ),
        migrations.RemoveConstraint(
            model_name='collectioncard',
            name='unique_collection_card_per_user_and_season',
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='rarity',
            field=models.CharField(blank=True, help_text='Rareté de la carte obtenue.', max_length=32),
        ),
        migrations.AddField(
            model_name='collectioncard',
            name='variant',
            field=models.CharField(blank=True, help_text='Numéro de la carte dans le set, quand une espèce y existe en plusieurs raretés. Vide pour une saison à une carte par espèce.', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='collectioncard',
            constraint=models.UniqueConstraint(fields=('user', 'pokemon_card', 'season', 'variant'), name='unique_collection_card_per_user_season_and_variant'),
        ),
    ]
