# Generated by Django 6.0.7 on 2026-08-04 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0010_types_reels_par_partie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SilhouetteGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=16)),
                ('round_count', models.PositiveSmallIntegerField(choices=[(5, '5 manches'), (10, '10 manches'), (15, '15 manches')], default=10, help_text="Nombre de manches choisi par l'hôte à la création du salon.")),
                ('turn_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SilhouettePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='silhouette.silhouettegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silhouette_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SilhouetteRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='silhouette.silhouettegame')),
                ('pokemon_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silhouette_rounds', to='game.pokemoncard')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SilhouetteGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('is_correct', models.BooleanField(default=False)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='silhouette.silhouetteplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='silhouette.silhouetteround')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='silhouetteplayer',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_silhouette_user_per_game'),
        ),
        migrations.AddConstraint(
            model_name='silhouetteround',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='unique_silhouette_round_number'),
        ),
        migrations.AddConstraint(
            model_name='silhouetteguess',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('round', 'player'), name='unique_correct_guess_per_round'),
        ),
    ]
